from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def _safe_div(num: pd.Series, den: pd.Series) -> pd.Series:
    den2 = den.replace(0, np.nan)
    return num / den2


def _label_from_scenario(s: str) -> str:
    parts = str(s).split("_H")
    if len(parts) == 2:
        scenario = parts[0]
        h = parts[1]
        return f"{scenario}\n{h}h"
    return str(s)


def _ensure_delta_columns(summary: pd.DataFrame) -> pd.DataFrame:
    out = summary.copy()
    needed = {
        "delta_exp_improve_pct_mean",
        "delta_resp_improve_pct_mean",
        "delta_comm_increase_pct_mean",
        "delta_model_done_gain_mean",
    }
    if needed.issubset(set(out.columns)):
        return out

    key_cols = ["exp_id", "scenario_id", "tune_id", "time_horizon_h"]
    p = out[out["baseline"] == "proposed"].copy()
    q = out[out["baseline"] == "prediction_only"].copy()
    pq = p.merge(q, on=key_cols, suffixes=("_proposed", "_prediction"), how="inner")
    if pq.empty:
        return out

    den_e = pq["value_weighted_exposure_mean_prediction"].replace(0.0, np.nan)
    den_r = pq["mean_response_time_s_mean_prediction"].replace(0.0, np.nan)
    den_c = pq["boundary_message_count_mean_prediction"].replace(0.0, np.nan)
    pq["delta_exp_improve_pct_mean"] = (
        100.0 * (pq["value_weighted_exposure_mean_prediction"] - pq["value_weighted_exposure_mean_proposed"]) / den_e
    )
    pq["delta_resp_improve_pct_mean"] = (
        100.0 * (pq["mean_response_time_s_mean_prediction"] - pq["mean_response_time_s_mean_proposed"]) / den_r
    )
    pq["delta_comm_increase_pct_mean"] = (
        100.0 * (pq["boundary_message_count_mean_proposed"] - pq["boundary_message_count_mean_prediction"]) / den_c
    )
    pq["delta_model_done_gain_mean"] = (
        pq["deterring_actions_completed_model_scored_mean_proposed"]
        - pq["deterring_actions_completed_model_scored_mean_prediction"]
    )
    keep = key_cols + list(needed)
    out = out.merge(pq[keep], on=key_cols, how="left")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot thesis key metrics from summary CSV.")
    parser.add_argument(
        "--summary-csv",
        default="thesis_summary_24h_sweep_parallel_fast_diagnostic_like.csv",
        help="Summary CSV generated by run_24h_experiment_parallel.py",
    )
    parser.add_argument(
        "--outdir",
        default="results/key_metrics",
        help="Folder where key plots and summary markdown are saved",
    )
    args = parser.parse_args()

    summary_csv = Path(args.summary_csv)
    if not summary_csv.exists():
        raise FileNotFoundError(f"Missing summary CSV: {summary_csv}")

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    summary = pd.read_csv(summary_csv)
    summary = _ensure_delta_columns(summary)

    if "baseline" in summary.columns:
        proposed = summary[summary["baseline"] == "proposed"].copy()
    else:
        proposed = summary.copy()
    proposed = proposed.sort_values(["scenario_id"]).reset_index(drop=True)
    proposed["label"] = proposed["scenario_id"].map(_label_from_scenario)

    required = [
        "delta_exp_improve_pct_mean",
        "delta_resp_improve_pct_mean",
        "delta_comm_increase_pct_mean",
        "delta_model_done_gain_mean",
    ]
    for c in required:
        if c not in proposed.columns:
            raise ValueError(f"Required column missing after processing: {c}")

    # ---- Plot 1: primary outcomes with CI
    fig, axes = plt.subplots(1, 2, figsize=(13, 4.8), sharex=True)
    x = np.arange(len(proposed))

    exp_mean = proposed["delta_exp_improve_pct_mean"].to_numpy(dtype=float)
    exp_ci = proposed.get("delta_exp_improve_pct_ci95", pd.Series(np.nan, index=proposed.index)).to_numpy(dtype=float)
    exp_colors = ["#2ca02c" if v > 0 else "#d62728" for v in exp_mean]
    axes[0].bar(x, exp_mean, color=exp_colors, alpha=0.85)
    axes[0].errorbar(x, exp_mean, yerr=exp_ci, fmt="none", color="black", capsize=4, linewidth=1.2)
    axes[0].axhline(0.0, color="black", linestyle="--", linewidth=1)
    axes[0].set_title("Exposure Improvement vs Prediction-Only")
    axes[0].set_ylabel("delta exposure [%] (higher better)")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(proposed["label"], rotation=0)
    axes[0].grid(axis="y", alpha=0.25)

    resp_mean = proposed["delta_resp_improve_pct_mean"].to_numpy(dtype=float)
    resp_ci = proposed.get("delta_resp_improve_pct_ci95", pd.Series(np.nan, index=proposed.index)).to_numpy(dtype=float)
    resp_colors = ["#2ca02c" if v > 0 else "#d62728" for v in resp_mean]
    axes[1].bar(x, resp_mean, color=resp_colors, alpha=0.85)
    axes[1].errorbar(x, resp_mean, yerr=resp_ci, fmt="none", color="black", capsize=4, linewidth=1.2)
    axes[1].axhline(0.0, color="black", linestyle="--", linewidth=1)
    axes[1].set_title("Response-Time Improvement vs Prediction-Only")
    axes[1].set_ylabel("delta response [%] (higher better)")
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(proposed["label"], rotation=0)
    axes[1].grid(axis="y", alpha=0.25)
    fig.tight_layout()
    fig.savefig(outdir / "01_primary_outcomes_with_ci.png", dpi=180)
    plt.close(fig)

    # ---- Plot 2: communication penalty with CI and target
    fig, ax = plt.subplots(figsize=(8.6, 4.8))
    comm_mean = proposed["delta_comm_increase_pct_mean"].to_numpy(dtype=float)
    comm_ci = proposed.get("delta_comm_increase_pct_ci95", pd.Series(np.nan, index=proposed.index)).to_numpy(dtype=float)
    comm_colors = ["#2ca02c" if v <= 30.0 else "#ff7f0e" for v in comm_mean]
    ax.bar(x, comm_mean, color=comm_colors, alpha=0.9)
    ax.errorbar(x, comm_mean, yerr=comm_ci, fmt="none", color="black", capsize=4, linewidth=1.2)
    ax.axhline(30.0, color="red", linestyle="--", linewidth=1.2, label="target +30%")
    ax.set_title("Communication Increase vs Prediction-Only")
    ax.set_ylabel("delta communication [%] (lower better)")
    ax.set_xticks(x)
    ax.set_xticklabels(proposed["label"])
    ax.grid(axis="y", alpha=0.25)
    ax.legend(loc="upper left")
    fig.tight_layout()
    fig.savefig(outdir / "02_communication_penalty_with_ci.png", dpi=180)
    plt.close(fig)

    # ---- Plot 3: tradeoff view (comm vs exposure) with scenario labels
    fig, ax = plt.subplots(figsize=(8.6, 5.2))
    ax.axhline(0.0, color="black", linestyle="--", linewidth=1)
    ax.axvline(30.0, color="red", linestyle="--", linewidth=1.2, label="target +30% comm")
    for i, row in proposed.iterrows():
        x0 = float(row["delta_comm_increase_pct_mean"])
        y0 = float(row["delta_exp_improve_pct_mean"])
        ax.scatter(x0, y0, s=80, color="#1f77b4")
        ax.annotate(row["label"], (x0, y0), textcoords="offset points", xytext=(6, 3), fontsize=8)
    ax.set_title("Tradeoff: Exposure Improvement vs Communication Increase")
    ax.set_xlabel("delta communication [%] (left is better)")
    ax.set_ylabel("delta exposure [%] (up is better)")
    ax.grid(alpha=0.25)
    ax.legend(loc="upper right")
    fig.tight_layout()
    fig.savefig(outdir / "03_tradeoff_exposure_vs_communication.png", dpi=180)
    plt.close(fig)

    # ---- Plot 4: preventive funnel conversion rates (proposed only)
    cands = proposed.get("model_deterring_candidates_total_mean", pd.Series(np.nan, index=proposed.index))
    pass_risk = proposed.get("model_deterring_pass_risk_mean", pd.Series(np.nan, index=proposed.index))
    pass_support = proposed.get("model_deterring_pass_support_mean", pd.Series(np.nan, index=proposed.index))
    accepted = proposed.get("model_deterring_accepted_mean", pd.Series(np.nan, index=proposed.index))
    generated = proposed.get("model_deterring_generated_mean", pd.Series(np.nan, index=proposed.index))
    completed = proposed.get("deterring_actions_completed_model_scored_mean", pd.Series(np.nan, index=proposed.index))

    rates = pd.DataFrame(
        {
            "risk_pass": _safe_div(pass_risk, cands),
            "support_pass": _safe_div(pass_support, pass_risk),
            "accept_given_support": _safe_div(accepted, pass_support),
            "generated_given_accept": _safe_div(generated, accepted),
            "completed_given_generated": _safe_div(completed, generated),
        },
        index=proposed["label"],
    )

    fig, ax = plt.subplots(figsize=(10.8, 4.8))
    im = ax.imshow(rates.fillna(0.0).to_numpy(dtype=float), aspect="auto", vmin=0.0, vmax=1.0, cmap="YlGnBu")
    ax.set_title("Model-Scored Deterrence Funnel Conversion Rates (Proposed)")
    ax.set_xticks(range(len(rates.columns)))
    ax.set_xticklabels(rates.columns, rotation=25, ha="right")
    ax.set_yticks(range(len(rates.index)))
    ax.set_yticklabels(rates.index)
    for i in range(rates.shape[0]):
        for j in range(rates.shape[1]):
            v = rates.iloc[i, j]
            txt = "nan" if pd.isna(v) else f"{100.0*v:.1f}%"
            ax.text(j, i, txt, ha="center", va="center", fontsize=8, color="black")
    fig.colorbar(im, ax=ax, fraction=0.032, pad=0.02, label="rate")
    fig.tight_layout()
    fig.savefig(outdir / "04_preventive_funnel_conversion_rates.png", dpi=180)
    plt.close(fig)

    # ---- Write concise metric rationale markdown
    md = []
    md.append("# Key Metrics Chosen")
    md.append("")
    md.append("1. **Exposure improvement (with CI)**")
    md.append("- Primary thesis objective is reducing value-weighted exposure.")
    md.append("- CI is required to avoid over-trusting seed noise.")
    md.append("")
    md.append("2. **Response-time improvement (with CI)**")
    md.append("- Exposure gains are less credible if achieved by delaying response.")
    md.append("- This guards against planner choices that starve urgent tasks.")
    md.append("")
    md.append("3. **Communication increase (with CI) vs +30% target**")
    md.append("- Your deployment constraint explicitly includes communication overhead.")
    md.append("- Plotting against the target line makes pass/fail obvious.")
    md.append("")
    md.append("4. **Preventive funnel conversion rates**")
    md.append("- Diagnoses where model-scored deterrence dies: risk gate, support gate, acceptance, dispatch, completion.")
    md.append("- This is the most direct way to debug why proposed is (or is not) outperforming.")
    md.append("")
    md.append("## Caution")
    md.append("- Forecast metrics are currently near-zero/NaN in your runs, so they are not decision-driving yet.")
    md.append("- Composite rank is useful for dashboards, but less defensible than objective-specific metrics with CIs.")
    (outdir / "KEY_METRICS_README.md").write_text("\n".join(md), encoding="utf-8")

    print(f"[done] key metric plots written to: {outdir.resolve()}")


if __name__ == "__main__":
    main()

